# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de337f2d5087b842c8ba224952e9b1e9def1bf19cb78d1e9aa76c0d5c3e28e5879fe06b256b772a3d76fac9f7f96737be502804e3fff6cf4f7935f7664d3a2ff

test:
  secret_key_base: f9d314b3984921c1984612f3a10c51893112126c8023644a94df848c0ea5f3264e059970df0b4cd057b314cbed08846cb02124896ced6deb19b285636b45ab04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
